# Generated by Django 6.0 on 2025-12-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='공사명', max_length=200)),
                ('location', models.CharField(blank=True, help_text='현장위치', max_length=300)),
                ('contractor', models.CharField(blank=True, help_text='시공사', max_length=100)),
                ('report_background', models.FileField(help_text='빈 PDF 양식 파일', null=True, upload_to='templates/')),
                ('plan_file', models.FileField(help_text='계측계획평면도', null=True, upload_to='plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('T', '건물경사계'), ('CK', '균열측정기'), ('I', '지중경사계'), ('S', '변형률계'), ('W', '지하수위계')], max_length=5)),
                ('code', models.CharField(max_length=20)),
                ('initial_value', models.FloatField(blank=True, help_text='초기 측정값', null=True)),
                ('initial_date', models.DateField(blank=True, null=True)),
                ('limit_warning', models.FloatField(default=0.0, help_text='1차 관리치(주의)')),
                ('limit_danger', models.FloatField(default=0.0, help_text='2차 관리치(위험)')),
                ('pdf_x', models.FloatField(default=0.0, help_text='PDF 오버레이용 X좌표')),
                ('pdf_y', models.FloatField(default=0.0, help_text='PDF 오버레이용 Y좌표')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='reports.project')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_date', models.DateField()),
                ('value', models.FloatField(blank=True, help_text='금회 측정값', null=True)),
                ('displacement', models.FloatField(blank=True, help_text='변위량(Current-Initial)', null=True)),
                ('raw_json', models.JSONField(blank=True, help_text='지중경사계 심도별 데이터', null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='reports.sensor')),
            ],
            options={
                'unique_together': {('sensor', 'measure_date')},
            },
        ),
    ]
